version: '3.8'

services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/postgres -schemas=public -user=postgres -password=password  -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: library/postgres:12.6-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
