# This is a basic workflow to help you get started with Actions

name: Create database docments

on:
  push:
    branches:
      - main
    paths:
      - 'db/**'
  workflow_dispatch:

jobs:
  create_documents:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: docker-compose up -d

      - name: Create database documents
        run: docker run --user root --rm --net="host" -v $PWD/schemaspy/output:/output -v $PWD/schemaspy/schemaspy.properties:/schemaspy.properties schemaspy/schemaspy:latest

      - name: commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Create"
          git push

      - run: docker-compose down
